// Generated by LiveScript 1.3.1
(function(){
  var d, test1;
  d = require('./index');
  test1 = function(){
    var makef, targets;
    makef = function(name){
      return function(arg, callback){
        console.log('running', name);
        setTimeout(function(){
          return callback(null, arg);
        }, 100);
      };
    };
    targets = {
      logger: {
        before: 'db',
        init: makef('logger')
      },
      db: {
        requires: 'blab',
        init: makef('db')
      },
      express: {
        after: 'db',
        init: makef('express')
      },
      blab: {
        init: makef('blab')
      }
    };
    return d.run(targets, 1);
  };
  test1();
}).call(this);
